services:
  web-api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: web-api
    build:
      context: .
      dockerfile: src/App/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"

  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      - POSTGRES_DB=clean-architecture
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  aspire:
    container_name: otel-dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    environment:
      - ASPIRE_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
      - Dashboard__ResourceServiceClient__AuthMode=Unsecured
      - ASPIRE_ALLOW_UNSECURED_TRANSPORT=true
    ports:
      - "4317:18889"
      - "4318:18890"
      - "18888:18888"

volumes:
  postgres_data: